name: scope2screen2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - Flask=2.1.0
  - flask-sqlalchemy=2.5.1
  - sqlalchemy=1.4.41
  - jinja2==3.0.3
  - werkzeug==2.0.3
  - itsdangerous==2.0.1
  - nomkl
  - numpy
  - opencv
  - orjson
  - pandas
  - pillow=8.1.1
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - waitress
  - zarr=2.10.1
  - pyinstaller
  - pip
  - pip:
      - ome-types==0.2.9
      - dask
      - dask[dataframe]
      - xmlschema==1.8.0




